import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "de" | "it" | "pt" | "gr" | "sp";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.features": "Features",
    "nav.howItWorks": "How It Works",
    "nav.pricing": "Pricing",
    "nav.downloadApp": "Download App",
    "nav.getStarted": "Get Started Free",
    // Hero
    "hero.badge": "Learn smarter, not harder",
    "hero.title": "Master Anything with",
    "hero.titleHighlight": "Smart Flashcards",
    "hero.description": "Create personalized flashcard decks, take quizzes, and learn new languages. Import from Excel or build from scratch. Start free today.",
    "hero.cta": "Start Learning Free",
    "hero.secondary": "See How It Works",
    "hero.freeDecks": "2 Free Decks",
    "hero.cardsEach": "50 Cards Each",
    "hero.noCard": "No Credit Card",
    // Features
    "features.title": "Everything You Need to Learn",
    "features.subtitle": "Powerful tools designed to make learning efficient, enjoyable, and effective.",
    "features.flashcardDecks": "Flashcard Decks",
    "features.flashcardDecksDesc": "Create unlimited decks organized by topic. Perfect for vocabulary, facts, or any subject you want to master.",
    "features.excelImport": "Excel Import",
    "features.excelImportDesc": "Already have your content? Import directly from Excel spreadsheets and start learning in seconds.",
    "features.smartQuizzes": "Smart Quizzes",
    "features.smartQuizzesDesc": "Test your knowledge with interactive quizzes. Track your progress and focus on what needs work.",
    "features.languageLearning": "Language Learning",
    "features.languageLearningDesc": "Built-in reading mode for language practice. Perfect for learning vocabulary in any language.",
    "features.spacedRepetition": "Spaced Repetition",
    "features.spacedRepetitionDesc": "Our algorithm shows cards at optimal intervals so you remember more with less effort.",
    "features.progressTracking": "Progress Tracking",
    "features.progressTrackingDesc": "See your improvement over time with detailed statistics and achievement badges.",
    // Pricing
    "pricing.title": "Simple, Transparent Pricing",
    "pricing.subtitle": "Start free and upgrade when you're ready. One-time payment, no subscriptions.",
    "pricing.free": "Free",
    "pricing.pro": "Pro",
    "pricing.ai": "AI Subscription",
    "pricing.forever": "forever",
    "pricing.oneTime": "one-time",
    "pricing.month": "/month",
    "pricing.comingSoon": "Coming Soon",
    "pricing.mostPopular": "Most Popular",
    "pricing.freeDesc": "Perfect to get started",
    "pricing.proDesc": "Pay once, learn forever",
    "pricing.aiDesc": "Coming Q1 2026",
    "pricing.startFree": "Start Free",
    "pricing.goPro": "Go Pro",
    "pricing.free.feature1": "2 card decks",
    "pricing.free.feature2": "50 cards per deck",
    "pricing.free.feature3": "Basic quizzes",
    "pricing.free.feature4": "Excel import",
    "pricing.free.feature5": "Progress tracking",
    "pricing.pro.feature1": "Unlimited decks & cards",
    "pricing.pro.feature2": "Excel import & export",
    "pricing.pro.feature3": "Advanced quizzes",
    "pricing.pro.feature4": "Spaced repetition",
    "pricing.pro.feature5": "Language reading mode",
    "pricing.pro.feature6": "Offline access",
    "pricing.pro.feature7": "No limits except your phone storage",
    "pricing.ai.feature1": "Everything in Pro",
    "pricing.ai.feature2": "AI-powered deck creation",
    "pricing.ai.feature3": "Use prompts to generate cards",
    "pricing.ai.feature4": "10,000 tokens per month",
    // How It Works
    "howItWorks.title": "How It Works",
    "howItWorks.subtitle": "Get started in minutes and begin your learning journey today.",
    "howItWorks.step1Title": "Quick Test or My Decks",
    "howItWorks.step1Desc": "Start immediately with a quick test or browse your personal deck library.",
    "howItWorks.step2Title": "Organize Your Decks",
    "howItWorks.step2Desc": "Create decks by topic with tags. Keep active decks separate from archived ones.",
    "howItWorks.step3Title": "Study or Quiz",
    "howItWorks.step3Desc": "Flip through cards in Study mode or test yourself with Quiz. Track new vs learned cards.",
    "howItWorks.step4Title": "Customize Your Experience",
    "howItWorks.step4Desc": "Set your language, daily session size, and learning preferences to match your goals.",
    // Examples
    "examples.title": "Examples",
    "examples.subtitle": "Download ready-made verb lists and start practicing immediately.",
    "examples.item1.title": "50 Daily Verbs: English → Portuguese",
    "examples.item1.desc": "Common verbs translated for everyday conversations.",
    "examples.item2.title": "50 Daily Verbs: English → Italian",
    "examples.item2.desc": "Core verbs for quick Italian practice.",
    "examples.item3.title": "50 Daily Verbs: English → Greek",
    "examples.item3.desc": "Essential verbs for beginner study.",
    "examples.item4.title": "50 Daily Verbs: English → German",
    "examples.item4.desc": "High-frequency verbs for daily use.",
    "examples.item1.download": "Download Portuguese list",
    "examples.item2.download": "Download Italian list",
    "examples.item3.download": "Download Greek list",
    "examples.item4.download": "Download German list",
    // Footer
    "footer.tagline": "Master anything with smart flashcards. Learn smarter, not harder.",
    "footer.product": "Product",
    "footer.support": "Support",
    "footer.legal": "Legal",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.examples": "Examples",
    "footer.downloadApp": "Download App",
    "footer.helpCenter": "Help Center",
    "footer.contact": "Contact Us",
    "footer.faq": "FAQ",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.imprint": "Imprint",
  },
  de: {
    "nav.features": "Funktionen",
    "nav.howItWorks": "So funktioniert's",
    "nav.pricing": "Preise",
    "nav.downloadApp": "App herunterladen",
    "nav.getStarted": "Kostenlos starten",
    "hero.badge": "Lernen Sie klüger, nicht härter",
    "hero.title": "Meistere alles mit",
    "hero.titleHighlight": "Smarten Lernkarten",
    "hero.description": "Erstellen Sie personalisierte Lernkarten-Decks, machen Sie Quizze und lernen Sie neue Sprachen. Importieren Sie aus Excel oder erstellen Sie von Grund auf. Starten Sie heute kostenlos.",
    "hero.cta": "Kostenlos lernen",
    "hero.secondary": "So funktioniert's",
    "hero.freeDecks": "2 Gratis-Decks",
    "hero.cardsEach": "50 Karten je Deck",
    "hero.noCard": "Keine Kreditkarte",
    "features.title": "Alles was Sie zum Lernen brauchen",
    "features.subtitle": "Leistungsstarke Tools für effizientes, angenehmes und effektives Lernen.",
    "features.flashcardDecks": "Lernkarten-Decks",
    "features.flashcardDecksDesc": "Erstellen Sie unbegrenzte Decks nach Themen. Perfekt für Vokabeln, Fakten oder jedes Thema.",
    "features.excelImport": "Excel-Import",
    "features.excelImportDesc": "Haben Sie bereits Inhalte? Importieren Sie direkt aus Excel und lernen Sie in Sekunden.",
    "features.smartQuizzes": "Smarte Quizze",
    "features.smartQuizzesDesc": "Testen Sie Ihr Wissen mit interaktiven Quizzen. Verfolgen Sie Ihren Fortschritt.",
    "features.languageLearning": "Sprachenlernen",
    "features.languageLearningDesc": "Eingebauter Lesemodus für Sprachpraxis. Perfekt zum Vokabellernen in jeder Sprache.",
    "features.spacedRepetition": "Verteiltes Wiederholen",
    "features.spacedRepetitionDesc": "Unser Algorithmus zeigt Karten in optimalen Abständen, damit Sie mehr behalten.",
    "features.progressTracking": "Fortschrittsverfolgung",
    "features.progressTrackingDesc": "Sehen Sie Ihre Verbesserung mit detaillierten Statistiken und Erfolgsabzeichen.",
    "pricing.title": "Einfache, transparente Preise",
    "pricing.subtitle": "Starten Sie kostenlos und upgraden Sie, wenn Sie bereit sind. Einmalzahlung, keine Abos.",
    "pricing.free": "Kostenlos",
    "pricing.pro": "Pro",
    "pricing.ai": "KI-Abo",
    "pricing.forever": "für immer",
    "pricing.oneTime": "einmalig",
    "pricing.month": "/Monat",
    "pricing.comingSoon": "Demnächst",
    "pricing.mostPopular": "Am beliebtesten",
    "pricing.freeDesc": "Perfekt zum Starten",
    "pricing.proDesc": "Einmal zahlen, für immer lernen",
    "pricing.aiDesc": "Kommt Q1 2026",
    "pricing.startFree": "Kostenlos starten",
    "pricing.goPro": "Pro werden",
    "pricing.free.feature1": "2 Kartendecks",
    "pricing.free.feature2": "50 Karten pro Deck",
    "pricing.free.feature3": "Basis-Quizze",
    "pricing.free.feature4": "Excel-Import",
    "pricing.free.feature5": "Fortschrittsverfolgung",
    "pricing.pro.feature1": "Unbegrenzte Decks & Karten",
    "pricing.pro.feature2": "Excel-Import & Export",
    "pricing.pro.feature3": "Erweiterte Quizze",
    "pricing.pro.feature4": "Verteiltes Wiederholen",
    "pricing.pro.feature5": "Sprach-Lesemodus",
    "pricing.pro.feature6": "Offline-Zugang",
    "pricing.pro.feature7": "Keine Limits außer Ihrem Speicher",
    "pricing.ai.feature1": "Alles aus Pro",
    "pricing.ai.feature2": "KI-gestützte Deck-Erstellung",
    "pricing.ai.feature3": "Prompts zum Generieren von Karten",
    "pricing.ai.feature4": "10.000 Tokens pro Monat",
    "howItWorks.title": "So funktioniert's",
    "howItWorks.subtitle": "Starten Sie in wenigen Minuten und beginnen Sie Ihre Lernreise noch heute.",
    "howItWorks.step1Title": "Schnelltest oder Meine Decks",
    "howItWorks.step1Desc": "Starten Sie sofort mit einem Schnelltest oder durchsuchen Sie Ihre Deck-Bibliothek.",
    "howItWorks.step2Title": "Decks organisieren",
    "howItWorks.step2Desc": "Erstellen Sie Decks nach Themen mit Tags. Aktive und archivierte Decks getrennt.",
    "howItWorks.step3Title": "Lernen oder Quiz",
    "howItWorks.step3Desc": "Blättern Sie durch Karten im Lernmodus oder testen Sie sich im Quiz.",
    "howItWorks.step4Title": "Anpassen",
    "howItWorks.step4Desc": "Stellen Sie Sprache, Sitzungsgröße und Lernpräferenzen nach Ihren Zielen ein.",
    "examples.title": "Beispiele",
    "examples.subtitle": "Laden Sie fertige Verb-Listen herunter und üben Sie sofort.",
    "examples.item1.title": "50 tägliche Verben: Englisch → Portugiesisch",
    "examples.item1.desc": "Häufige Verben für den Alltag übersetzt.",
    "examples.item2.title": "50 tägliche Verben: Englisch → Italienisch",
    "examples.item2.desc": "Wichtige Verben für schnelles Italienisch-Training.",
    "examples.item3.title": "50 tägliche Verben: Englisch → Griechisch",
    "examples.item3.desc": "Grundlegende Verben für Anfänger.",
    "examples.item4.title": "50 tägliche Verben: Englisch → Deutsch",
    "examples.item4.desc": "Hochfrequente Verben für den täglichen Gebrauch.",
    "examples.item1.download": "Portugiesisch-Liste herunterladen",
    "examples.item2.download": "Italienisch-Liste herunterladen",
    "examples.item3.download": "Griechisch-Liste herunterladen",
    "examples.item4.download": "Deutsch-Liste herunterladen",
    "footer.tagline": "Meistere alles mit smarten Lernkarten. Lerne smarter, nicht härter.",
    "footer.product": "Produkt",
    "footer.support": "Support",
    "footer.legal": "Rechtliches",
    "footer.features": "Funktionen",
    "footer.pricing": "Preise",
    "footer.examples": "Beispiele",
    "footer.downloadApp": "App herunterladen",
    "footer.helpCenter": "Hilfe-Center",
    "footer.contact": "Kontakt",
    "footer.faq": "FAQ",
    "footer.privacy": "Datenschutz",
    "footer.terms": "Nutzungsbedingungen",
    "footer.imprint": "Impressum",
  },
  it: {
    "nav.features": "Funzionalità",
    "nav.howItWorks": "Come funziona",
    "nav.pricing": "Prezzi",
    "nav.downloadApp": "Scarica l'app",
    "nav.getStarted": "Inizia gratis",
    "hero.badge": "Impara in modo più intelligente",
    "hero.title": "Padroneggia tutto con",
    "hero.titleHighlight": "Flashcard intelligenti",
    "hero.description": "Crea mazzi di flashcard personalizzati, fai quiz e impara nuove lingue. Importa da Excel o crea da zero. Inizia gratis oggi.",
    "hero.cta": "Inizia a imparare gratis",
    "hero.secondary": "Scopri come funziona",
    "hero.freeDecks": "2 mazzi gratis",
    "hero.cardsEach": "50 carte ciascuno",
    "hero.noCard": "Nessuna carta di credito",
    "features.title": "Tutto ciò di cui hai bisogno per imparare",
    "features.subtitle": "Strumenti potenti progettati per rendere l'apprendimento efficiente e piacevole.",
    "features.flashcardDecks": "Mazzi di Flashcard",
    "features.flashcardDecksDesc": "Crea mazzi illimitati organizzati per argomento. Perfetto per vocaboli e fatti.",
    "features.excelImport": "Importa da Excel",
    "features.excelImportDesc": "Hai già i tuoi contenuti? Importa direttamente da Excel e inizia a imparare.",
    "features.smartQuizzes": "Quiz Intelligenti",
    "features.smartQuizzesDesc": "Metti alla prova le tue conoscenze con quiz interattivi. Monitora i progressi.",
    "features.languageLearning": "Apprendimento Lingue",
    "features.languageLearningDesc": "Modalità lettura integrata per la pratica linguistica. Perfetto per il vocabolario.",
    "features.spacedRepetition": "Ripetizione Spaziata",
    "features.spacedRepetitionDesc": "Il nostro algoritmo mostra le carte a intervalli ottimali per ricordare di più.",
    "features.progressTracking": "Monitoraggio Progressi",
    "features.progressTrackingDesc": "Vedi i tuoi miglioramenti con statistiche dettagliate e badge.",
    "pricing.title": "Prezzi semplici e trasparenti",
    "pricing.subtitle": "Inizia gratis e aggiorna quando sei pronto. Pagamento unico, nessun abbonamento.",
    "pricing.free": "Gratis",
    "pricing.pro": "Pro",
    "pricing.ai": "Abbonamento IA",
    "pricing.forever": "per sempre",
    "pricing.oneTime": "una tantum",
    "pricing.month": "/mese",
    "pricing.comingSoon": "Prossimamente",
    "pricing.mostPopular": "Più popolare",
    "pricing.freeDesc": "Perfetto per iniziare",
    "pricing.proDesc": "Paga una volta, impara per sempre",
    "pricing.aiDesc": "In arrivo Q1 2026",
    "pricing.startFree": "Inizia gratis",
    "pricing.goPro": "Passa a Pro",
    "pricing.free.feature1": "2 mazzi di carte",
    "pricing.free.feature2": "50 carte per mazzo",
    "pricing.free.feature3": "Quiz base",
    "pricing.free.feature4": "Importazione Excel",
    "pricing.free.feature5": "Monitoraggio progressi",
    "pricing.pro.feature1": "Mazzi e carte illimitati",
    "pricing.pro.feature2": "Import & export Excel",
    "pricing.pro.feature3": "Quiz avanzati",
    "pricing.pro.feature4": "Ripetizione spaziata",
    "pricing.pro.feature5": "Modalità lettura lingue",
    "pricing.pro.feature6": "Accesso offline",
    "pricing.pro.feature7": "Nessun limite tranne la memoria",
    "pricing.ai.feature1": "Tutto in Pro",
    "pricing.ai.feature2": "Creazione mazzi con IA",
    "pricing.ai.feature3": "Usa prompt per generare carte",
    "pricing.ai.feature4": "10.000 token al mese",
    "howItWorks.title": "Come funziona",
    "howItWorks.subtitle": "Inizia in pochi minuti e comincia il tuo percorso di apprendimento oggi.",
    "howItWorks.step1Title": "Test rapido o I miei mazzi",
    "howItWorks.step1Desc": "Inizia subito con un test rapido o sfoglia la tua libreria di mazzi.",
    "howItWorks.step2Title": "Organizza i tuoi mazzi",
    "howItWorks.step2Desc": "Crea mazzi per argomento con tag. Separa mazzi attivi e archiviati.",
    "howItWorks.step3Title": "Studia o Quiz",
    "howItWorks.step3Desc": "Sfoglia le carte in modalità Studio o mettiti alla prova con il Quiz.",
    "howItWorks.step4Title": "Personalizza",
    "howItWorks.step4Desc": "Imposta lingua, dimensione sessione e preferenze di apprendimento.",
    "examples.title": "Esempi",
    "examples.subtitle": "Scarica liste di verbi pronte e inizia subito a praticare.",
    "examples.item1.title": "50 verbi quotidiani: inglese → portoghese",
    "examples.item1.desc": "Verbi comuni tradotti per l'uso quotidiano.",
    "examples.item2.title": "50 verbi quotidiani: inglese → italiano",
    "examples.item2.desc": "Verbi essenziali per esercitarsi velocemente.",
    "examples.item3.title": "50 verbi quotidiani: inglese → greco",
    "examples.item3.desc": "Verbi di base per principianti.",
    "examples.item4.title": "50 verbi quotidiani: inglese → tedesco",
    "examples.item4.desc": "Verbi ad alta frequenza per l'uso quotidiano.",
    "examples.item1.download": "Scarica la lista in portoghese",
    "examples.item2.download": "Scarica la lista in italiano",
    "examples.item3.download": "Scarica la lista in greco",
    "examples.item4.download": "Scarica la lista in tedesco",
    "footer.tagline": "Domina qualsiasi cosa con flashcard intelligenti. Impara in modo più intelligente.",
    "footer.product": "Prodotto",
    "footer.support": "Supporto",
    "footer.legal": "Legale",
    "footer.features": "Funzionalità",
    "footer.pricing": "Prezzi",
    "footer.examples": "Esempi",
    "footer.downloadApp": "Scarica l'app",
    "footer.helpCenter": "Centro assistenza",
    "footer.contact": "Contattaci",
    "footer.faq": "FAQ",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Termini di servizio",
    "footer.imprint": "Impressum",
  },
  pt: {
    "nav.features": "Recursos",
    "nav.howItWorks": "Como funciona",
    "nav.pricing": "Preços",
    "nav.downloadApp": "Baixar app",
    "nav.getStarted": "Começar grátis",
    "hero.badge": "Aprenda de forma mais inteligente",
    "hero.title": "Domine tudo com",
    "hero.titleHighlight": "Flashcards inteligentes",
    "hero.description": "Crie baralhos de flashcards personalizados, faça quizzes e aprenda novos idiomas. Importe do Excel ou crie do zero. Comece grátis hoje.",
    "hero.cta": "Começar a aprender grátis",
    "hero.secondary": "Veja como funciona",
    "hero.freeDecks": "2 baralhos grátis",
    "hero.cardsEach": "50 cartões cada",
    "hero.noCard": "Sem cartão de crédito",
    "features.title": "Tudo o que você precisa para aprender",
    "features.subtitle": "Ferramentas poderosas projetadas para tornar o aprendizado eficiente e agradável.",
    "features.flashcardDecks": "Baralhos de Flashcards",
    "features.flashcardDecksDesc": "Crie baralhos ilimitados organizados por tema. Perfeito para vocabulário e fatos.",
    "features.excelImport": "Importar do Excel",
    "features.excelImportDesc": "Já tem seu conteúdo? Importe diretamente do Excel e comece a aprender.",
    "features.smartQuizzes": "Quizzes Inteligentes",
    "features.smartQuizzesDesc": "Teste seu conhecimento com quizzes interativos. Acompanhe seu progresso.",
    "features.languageLearning": "Aprendizado de Idiomas",
    "features.languageLearningDesc": "Modo de leitura integrado para prática de idiomas. Perfeito para vocabulário.",
    "features.spacedRepetition": "Repetição Espaçada",
    "features.spacedRepetitionDesc": "Nosso algoritmo mostra cartões em intervalos ideais para lembrar mais.",
    "features.progressTracking": "Acompanhamento de Progresso",
    "features.progressTrackingDesc": "Veja sua melhoria com estatísticas detalhadas e medalhas.",
    "pricing.title": "Preços simples e transparentes",
    "pricing.subtitle": "Comece grátis e faça upgrade quando estiver pronto. Pagamento único, sem assinaturas.",
    "pricing.free": "Grátis",
    "pricing.pro": "Pro",
    "pricing.ai": "Assinatura IA",
    "pricing.forever": "para sempre",
    "pricing.oneTime": "único",
    "pricing.month": "/mês",
    "pricing.comingSoon": "Em breve",
    "pricing.mostPopular": "Mais popular",
    "pricing.freeDesc": "Perfeito para começar",
    "pricing.proDesc": "Pague uma vez, aprenda para sempre",
    "pricing.aiDesc": "Chegando Q1 2026",
    "pricing.startFree": "Começar grátis",
    "pricing.goPro": "Ir para Pro",
    "pricing.free.feature1": "2 baralhos de cartões",
    "pricing.free.feature2": "50 cartões por baralho",
    "pricing.free.feature3": "Quizzes básicos",
    "pricing.free.feature4": "Importação Excel",
    "pricing.free.feature5": "Acompanhamento de progresso",
    "pricing.pro.feature1": "Baralhos e cartões ilimitados",
    "pricing.pro.feature2": "Import e export Excel",
    "pricing.pro.feature3": "Quizzes avançados",
    "pricing.pro.feature4": "Repetição espaçada",
    "pricing.pro.feature5": "Modo leitura de idiomas",
    "pricing.pro.feature6": "Acesso offline",
    "pricing.pro.feature7": "Sem limites exceto armazenamento",
    "pricing.ai.feature1": "Tudo do Pro",
    "pricing.ai.feature2": "Criação de baralhos com IA",
    "pricing.ai.feature3": "Use prompts para gerar cartões",
    "pricing.ai.feature4": "10.000 tokens por mês",
    "howItWorks.title": "Como funciona",
    "howItWorks.subtitle": "Comece em minutos e inicie sua jornada de aprendizado hoje.",
    "howItWorks.step1Title": "Teste rápido ou Meus baralhos",
    "howItWorks.step1Desc": "Comece imediatamente com um teste rápido ou navegue pela sua biblioteca.",
    "howItWorks.step2Title": "Organize seus baralhos",
    "howItWorks.step2Desc": "Crie baralhos por tema com tags. Separe ativos dos arquivados.",
    "howItWorks.step3Title": "Estude ou Quiz",
    "howItWorks.step3Desc": "Navegue pelos cartões no modo Estudo ou teste-se no Quiz.",
    "howItWorks.step4Title": "Personalize",
    "howItWorks.step4Desc": "Configure idioma, tamanho da sessão e preferências de aprendizado.",
    "examples.title": "Exemplos",
    "examples.subtitle": "Baixe listas prontas de verbos e pratique imediatamente.",
    "examples.item1.title": "50 verbos diários: inglês → português",
    "examples.item1.desc": "Verbos comuns traduzidos para o dia a dia.",
    "examples.item2.title": "50 verbos diários: inglês → italiano",
    "examples.item2.desc": "Verbos essenciais para prática rápida.",
    "examples.item3.title": "50 verbos diários: inglês → grego",
    "examples.item3.desc": "Verbos básicos para iniciantes.",
    "examples.item4.title": "50 verbos diários: inglês → alemão",
    "examples.item4.desc": "Verbos de alta frequência para uso diário.",
    "examples.item1.download": "Baixar lista em português",
    "examples.item2.download": "Baixar lista em italiano",
    "examples.item3.download": "Baixar lista em grego",
    "examples.item4.download": "Baixar lista em alemão",
    "footer.tagline": "Domine tudo com flashcards inteligentes. Aprenda de forma mais inteligente.",
    "footer.product": "Produto",
    "footer.support": "Suporte",
    "footer.legal": "Legal",
    "footer.features": "Recursos",
    "footer.pricing": "Preços",
    "footer.examples": "Exemplos",
    "footer.downloadApp": "Baixar app",
    "footer.helpCenter": "Centro de Ajuda",
    "footer.contact": "Fale conosco",
    "footer.faq": "FAQ",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de serviço",
    "footer.imprint": "Impressum",
  },
  gr: {
    "nav.features": "Χαρακτηριστικά",
    "nav.howItWorks": "Πώς λειτουργεί",
    "nav.pricing": "Τιμές",
    "nav.downloadApp": "Λήψη εφαρμογής",
    "nav.getStarted": "Ξεκινήστε δωρεάν",
    "hero.badge": "Μάθετε πιο έξυπνα",
    "hero.title": "Κατακτήστε τα πάντα με",
    "hero.titleHighlight": "Έξυπνες κάρτες",
    "hero.description": "Δημιουργήστε εξατομικευμένες δέσμες καρτών, κάντε κουίζ και μάθετε νέες γλώσσες. Εισαγωγή από Excel ή δημιουργία από την αρχή.",
    "hero.cta": "Ξεκινήστε δωρεάν",
    "hero.secondary": "Δείτε πώς λειτουργεί",
    "hero.freeDecks": "2 δωρεάν δέσμες",
    "hero.cardsEach": "50 κάρτες η καθεμία",
    "hero.noCard": "Χωρίς πιστωτική κάρτα",
    "features.title": "Όλα όσα χρειάζεστε για να μάθετε",
    "features.subtitle": "Ισχυρά εργαλεία σχεδιασμένα για αποτελεσματική μάθηση.",
    "features.flashcardDecks": "Δέσμες Καρτών",
    "features.flashcardDecksDesc": "Δημιουργήστε απεριόριστες δέσμες ανά θέμα. Ιδανικό για λεξιλόγιο.",
    "features.excelImport": "Εισαγωγή Excel",
    "features.excelImportDesc": "Έχετε ήδη περιεχόμενο; Εισαγωγή από Excel και ξεκινήστε αμέσως.",
    "features.smartQuizzes": "Έξυπνα Κουίζ",
    "features.smartQuizzesDesc": "Δοκιμάστε τις γνώσεις σας με διαδραστικά κουίζ. Παρακολουθήστε την πρόοδο.",
    "features.languageLearning": "Εκμάθηση Γλωσσών",
    "features.languageLearningDesc": "Ενσωματωμένη λειτουργία ανάγνωσης για εξάσκηση γλωσσών.",
    "features.spacedRepetition": "Διαστημική Επανάληψη",
    "features.spacedRepetitionDesc": "Ο αλγόριθμός μας δείχνει κάρτες σε βέλτιστα διαστήματα.",
    "features.progressTracking": "Παρακολούθηση Προόδου",
    "features.progressTrackingDesc": "Δείτε τη βελτίωσή σας με λεπτομερή στατιστικά.",
    "pricing.title": "Απλές, διαφανείς τιμές",
    "pricing.subtitle": "Ξεκινήστε δωρεάν και αναβαθμίστε όταν είστε έτοιμοι. Εφάπαξ πληρωμή.",
    "pricing.free": "Δωρεάν",
    "pricing.pro": "Pro",
    "pricing.ai": "Συνδρομή AI",
    "pricing.forever": "για πάντα",
    "pricing.oneTime": "εφάπαξ",
    "pricing.month": "/μήνα",
    "pricing.comingSoon": "Σύντομα",
    "pricing.mostPopular": "Πιο δημοφιλές",
    "pricing.freeDesc": "Ιδανικό για αρχή",
    "pricing.proDesc": "Πληρώστε μία φορά, μάθετε για πάντα",
    "pricing.aiDesc": "Έρχεται Q1 2026",
    "pricing.startFree": "Ξεκινήστε δωρεάν",
    "pricing.goPro": "Γίνετε Pro",
    "pricing.free.feature1": "2 δέσμες καρτών",
    "pricing.free.feature2": "50 κάρτες ανά δέσμη",
    "pricing.free.feature3": "Βασικά κουίζ",
    "pricing.free.feature4": "Εισαγωγή Excel",
    "pricing.free.feature5": "Παρακολούθηση προόδου",
    "pricing.pro.feature1": "Απεριόριστες δέσμες & κάρτες",
    "pricing.pro.feature2": "Εισαγωγή & εξαγωγή Excel",
    "pricing.pro.feature3": "Προηγμένα κουίζ",
    "pricing.pro.feature4": "Διαστημική επανάληψη",
    "pricing.pro.feature5": "Λειτουργία ανάγνωσης",
    "pricing.pro.feature6": "Πρόσβαση εκτός σύνδεσης",
    "pricing.pro.feature7": "Χωρίς όρια εκτός αποθήκευσης",
    "pricing.ai.feature1": "Όλα τα Pro",
    "pricing.ai.feature2": "Δημιουργία με AI",
    "pricing.ai.feature3": "Prompts για κάρτες",
    "pricing.ai.feature4": "10.000 tokens/μήνα",
    "howItWorks.title": "Πώς λειτουργεί",
    "howItWorks.subtitle": "Ξεκινήστε σε λίγα λεπτά και αρχίστε το ταξίδι μάθησής σας σήμερα.",
    "howItWorks.step1Title": "Γρήγορο τεστ ή Οι δέσμες μου",
    "howItWorks.step1Desc": "Ξεκινήστε αμέσως με γρήγορο τεστ ή περιηγηθείτε στη βιβλιοθήκη σας.",
    "howItWorks.step2Title": "Οργανώστε τις δέσμες",
    "howItWorks.step2Desc": "Δημιουργήστε δέσμες ανά θέμα με ετικέτες.",
    "howItWorks.step3Title": "Μελέτη ή Κουίζ",
    "howItWorks.step3Desc": "Ξεφυλλίστε κάρτες ή δοκιμάστε τον εαυτό σας με Κουίζ.",
    "howItWorks.step4Title": "Προσαρμογή",
    "howItWorks.step4Desc": "Ορίστε γλώσσα, μέγεθος συνεδρίας και προτιμήσεις μάθησης.",
    "examples.title": "Παραδείγματα",
    "examples.subtitle": "Κατεβάστε έτοιμες λίστες ρημάτων και ξεκινήστε άμεσα.",
    "examples.item1.title": "50 καθημερινά ρήματα: αγγλικά → πορτογαλικά",
    "examples.item1.desc": "Συχνά ρήματα για καθημερινή χρήση.",
    "examples.item2.title": "50 καθημερινά ρήματα: αγγλικά → ιταλικά",
    "examples.item2.desc": "Βασικά ρήματα για γρήγορη εξάσκηση.",
    "examples.item3.title": "50 καθημερινά ρήματα: αγγλικά → ελληνικά",
    "examples.item3.desc": "Ρήματα για αρχάριους.",
    "examples.item4.title": "50 καθημερινά ρήματα: αγγλικά → γερμανικά",
    "examples.item4.desc": "Ρήματα υψηλής συχνότητας για καθημερινή χρήση.",
    "examples.item1.download": "Λήψη λίστας πορτογαλικών",
    "examples.item2.download": "Λήψη λίστας ιταλικών",
    "examples.item3.download": "Λήψη λίστας ελληνικών",
    "examples.item4.download": "Λήψη λίστας γερμανικών",
    "footer.tagline": "Κατακτήστε τα πάντα με έξυπνες κάρτες. Μάθετε πιο έξυπνα.",
    "footer.product": "Προϊόν",
    "footer.support": "Υποστήριξη",
    "footer.legal": "Νομικά",
    "footer.features": "Χαρακτηριστικά",
    "footer.pricing": "Τιμές",
    "footer.examples": "Παραδείγματα",
    "footer.downloadApp": "Λήψη εφαρμογής",
    "footer.helpCenter": "Κέντρο βοήθειας",
    "footer.contact": "Επικοινωνήστε",
    "footer.faq": "FAQ",
    "footer.privacy": "Πολιτική απορρήτου",
    "footer.terms": "Όροι χρήσης",
    "footer.imprint": "Impressum",
  },
  sp: {
    "nav.features": "Características",
    "nav.howItWorks": "Cómo funciona",
    "nav.pricing": "Precios",
    "nav.downloadApp": "Descargar app",
    "nav.getStarted": "Empezar gratis",
    "hero.badge": "Aprende de forma más inteligente",
    "hero.title": "Domina todo con",
    "hero.titleHighlight": "Tarjetas inteligentes",
    "hero.description": "Crea mazos de tarjetas personalizados, haz cuestionarios y aprende nuevos idiomas. Importa desde Excel o crea desde cero. Empieza gratis hoy.",
    "hero.cta": "Empezar a aprender gratis",
    "hero.secondary": "Ver cómo funciona",
    "hero.freeDecks": "2 mazos gratis",
    "hero.cardsEach": "50 tarjetas cada uno",
    "hero.noCard": "Sin tarjeta de crédito",
    "features.title": "Todo lo que necesitas para aprender",
    "features.subtitle": "Herramientas potentes diseñadas para hacer el aprendizaje eficiente y agradable.",
    "features.flashcardDecks": "Mazos de Tarjetas",
    "features.flashcardDecksDesc": "Crea mazos ilimitados organizados por tema. Perfecto para vocabulario y datos.",
    "features.excelImport": "Importar desde Excel",
    "features.excelImportDesc": "¿Ya tienes tu contenido? Importa directamente desde Excel y empieza a aprender.",
    "features.smartQuizzes": "Cuestionarios Inteligentes",
    "features.smartQuizzesDesc": "Pon a prueba tus conocimientos con cuestionarios interactivos. Sigue tu progreso.",
    "features.languageLearning": "Aprendizaje de Idiomas",
    "features.languageLearningDesc": "Modo de lectura integrado para práctica de idiomas. Perfecto para vocabulario.",
    "features.spacedRepetition": "Repetición Espaciada",
    "features.spacedRepetitionDesc": "Nuestro algoritmo muestra tarjetas en intervalos óptimos para recordar más.",
    "features.progressTracking": "Seguimiento de Progreso",
    "features.progressTrackingDesc": "Ve tu mejora con estadísticas detalladas e insignias de logros.",
    "pricing.title": "Precios simples y transparentes",
    "pricing.subtitle": "Empieza gratis y mejora cuando estés listo. Pago único, sin suscripciones.",
    "pricing.free": "Gratis",
    "pricing.pro": "Pro",
    "pricing.ai": "Suscripción IA",
    "pricing.forever": "para siempre",
    "pricing.oneTime": "único",
    "pricing.month": "/mes",
    "pricing.comingSoon": "Próximamente",
    "pricing.mostPopular": "Más popular",
    "pricing.freeDesc": "Perfecto para empezar",
    "pricing.proDesc": "Paga una vez, aprende para siempre",
    "pricing.aiDesc": "Llegando Q1 2026",
    "pricing.startFree": "Empezar gratis",
    "pricing.goPro": "Ir a Pro",
    "pricing.free.feature1": "2 mazos de tarjetas",
    "pricing.free.feature2": "50 tarjetas por mazo",
    "pricing.free.feature3": "Cuestionarios básicos",
    "pricing.free.feature4": "Importación Excel",
    "pricing.free.feature5": "Seguimiento de progreso",
    "pricing.pro.feature1": "Mazos y tarjetas ilimitados",
    "pricing.pro.feature2": "Import y export Excel",
    "pricing.pro.feature3": "Cuestionarios avanzados",
    "pricing.pro.feature4": "Repetición espaciada",
    "pricing.pro.feature5": "Modo lectura de idiomas",
    "pricing.pro.feature6": "Acceso sin conexión",
    "pricing.pro.feature7": "Sin límites excepto almacenamiento",
    "pricing.ai.feature1": "Todo de Pro",
    "pricing.ai.feature2": "Creación de mazos con IA",
    "pricing.ai.feature3": "Usa prompts para generar tarjetas",
    "pricing.ai.feature4": "10.000 tokens al mes",
    "howItWorks.title": "Cómo funciona",
    "howItWorks.subtitle": "Comienza en minutos y emprende tu viaje de aprendizaje hoy.",
    "howItWorks.step1Title": "Test rápido o Mis mazos",
    "howItWorks.step1Desc": "Empieza inmediatamente con un test rápido o navega por tu biblioteca.",
    "howItWorks.step2Title": "Organiza tus mazos",
    "howItWorks.step2Desc": "Crea mazos por tema con etiquetas. Separa activos de archivados.",
    "howItWorks.step3Title": "Estudia o Cuestionario",
    "howItWorks.step3Desc": "Repasa tarjetas en modo Estudio o ponte a prueba con el Cuestionario.",
    "howItWorks.step4Title": "Personaliza",
    "howItWorks.step4Desc": "Configura idioma, tamaño de sesión y preferencias de aprendizaje.",
    "examples.title": "Ejemplos",
    "examples.subtitle": "Descarga listas de verbos ya hechas y practica al instante.",
    "examples.item1.title": "50 verbos diarios: inglés → portugués",
    "examples.item1.desc": "Verbos comunes traducidos para el uso diario.",
    "examples.item2.title": "50 verbos diarios: inglés → italiano",
    "examples.item2.desc": "Verbos esenciales para practicar rápido.",
    "examples.item3.title": "50 verbos diarios: inglés → griego",
    "examples.item3.desc": "Verbos básicos para principiantes.",
    "examples.item4.title": "50 verbos diarios: inglés → alemán",
    "examples.item4.desc": "Verbos de alta frecuencia para uso diario.",
    "examples.item1.download": "Descargar lista en portugués",
    "examples.item2.download": "Descargar lista en italiano",
    "examples.item3.download": "Descargar lista en griego",
    "examples.item4.download": "Descargar lista en alemán",
    "footer.tagline": "Domina todo con tarjetas inteligentes. Aprende de forma más inteligente.",
    "footer.product": "Producto",
    "footer.support": "Soporte",
    "footer.legal": "Legal",
    "footer.features": "Características",
    "footer.pricing": "Precios",
    "footer.examples": "Ejemplos",
    "footer.downloadApp": "Descargar app",
    "footer.helpCenter": "Centro de ayuda",
    "footer.contact": "Contáctanos",
    "footer.faq": "FAQ",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos del servicio",
    "footer.imprint": "Impressum",
  },
};

const languageNames: Record<Language, string> = {
  en: "English",
  de: "Deutsch",
  it: "Italiano",
  pt: "Português",
  gr: "Ελληνικά",
  sp: "Español",
};

const languageFlags: Record<Language, string> = {
  en: "🇬🇧",
  de: "🇩🇪",
  it: "🇮🇹",
  pt: "🇵🇹",
  gr: "🇬🇷",
  sp: "🇪🇸",
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function detectBrowserLanguage(): Language {
  const browserLang = navigator.language.split("-")[0].toLowerCase();
  const langMap: Record<string, Language> = {
    en: "en",
    de: "de",
    it: "it",
    pt: "pt",
    el: "gr",
    es: "sp",
  };
  return langMap[browserLang] || "en";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language;
    return saved || detectBrowserLanguage();
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // Fallback for HMR issues - return default values instead of throwing
    console.warn("useLanguage called outside LanguageProvider, using fallback");
    return {
      language: "en" as Language,
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
}

export { languageNames, languageFlags };
